# .github/workflows/build.yml
# argocd用のci.yml
on: 
  push:
    branches:
    - 'main'
    - 'develop'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # git commit and push
      - name: Commit files
        run: |
          git config --local user.email ${{ secrets.GH_EMAIL }}
          git config --local user.name ${{ secrets.GH_NAME }}
          git checkout release
          git merge ${{ github.head_ref }}

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: 'release'

      # docker build and push
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push aruku-api
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./api
          # imageとtagは適宜変更
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERIMAGE }}:latest
